version: "3"

services:
    app:
        build: .
        container_name: task-container
        image: node:12
        working_dir: /usr/src/nestjs-task-management
        restart: always
        command: bash -c "yarn install && yarn start:dev"
        environment:
            - POSTGRES_URI=postgres://db:5432/task_management
        volumes:
            - ./dist/:/usr/src/nestjs-task-management/dist/
            - ./package.json:/usr/src/nestjs-task-management/package.json
        ports:
            - "3000:3000"
        depends_on: 
            - db
        links:
            - db

    db:
        container_name: db-container
        image: postgres:11.5
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "5432:5433"
