version: "3.7"

services:
    app:
        container_name: task-container
        build: 
            context: .
            target: development
        working_dir: /usr/src/nestjs-task-management
        restart: always
        command: sh -c "yarn install && yarn start:dev"
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=task_management
        volumes:
            - .:/usr/src/nestjs-task-management/
            - ./package.json:/usr/src/nestjs-task-management/package.json
            - /usr/src/nestjs-task-management/node_modules
        ports:
            - "3000:3000"
        depends_on: 
            - db
        links:
            - db

    db:
        container_name: db-container
        image: postgres:11.5
        restart: always
        environment: 
            - PG_DATA=/var/lib/postgresql/data
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5433"

volumes:
    pgdata: